repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # ref
    hooks:
     - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-isort]
        #files: \.py$
        args: [--ignore=E501, --max-line-length=88]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]  # using Python 3.8+
