on:
    pull_request:
    push:
      branches:
        - main
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.12"
        - uses: pre-commit/action@v3.0.0
    tests:
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: install nox
              run: pip install nox
            - name: run nox
              run: nox -s tests